name: GitHub Actions Demo

on:
  push:
    branches: [main]
    paths-ignore: [.github/**]
  pull_request:
    branches: [main]
  schedule:
    - cron: 15 6 * * 0
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Branch name: ${{ github.ref }}"
        
      - uses: actions/checkout@v3.3.0
      
      - run: |
          echo "Contents of repository"
          tree
          
